import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@smartpark/ui/src/app/globals.css'
import { SessionProvider } from '@smartpark/ui/src/components/molecules/SessionProvider'
import { ApolloProvider } from '@smartpark/network/src/config/apollo'
import { MenuItem } from '@smartpark/util/types'
import { Header } from '@smartpark/ui/src/components/organisms/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const MENUITEMS: MenuItem[] = [
  { label: 'Search', href: '/search' },
  { label: 'Bookings', href: '/bookings' },
  { label: 'About', href: '/about' },
]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          <ApolloProvider>
            <Header menuItems={MENUITEMS} />
            {children}
          </ApolloProvider>
        </SessionProvider>
      </body>
    </html>
  )
}
