import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@smartpark/ui/src/app/globals.css'
import { SessionProvider } from '@smartpark/ui/src/components/molecules/SessionProvider'
import { ApolloProvider } from '@smartpark/network/src/config/apollo'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          <ApolloProvider>{children}</ApolloProvider>
        </SessionProvider>
      </body>
    </html>
  )
}
